library(attempt)
library(testthat)
test_that("multiplication works", {
  expect_null(leg_1_player$active)
  leg <- leg_1_player$new(player_name = "Leo", color = "#121212", 
                          total_score = 301, double_out = FALSE, 
                          reactive = FALSE)
  expect_equal(leg$remain(), 301)
  expect_equal(leg$round(), 0)
  expect_equal(leg$status(), "not started")
  leg$score(120)
  expect_equal(leg$remain(), 181)
  expect_equal(leg$round(), 1)
  leg$score_rest(120)
  expect_equal(leg$remain(), 120)
  expect_equal(leg$round(), 2)
  leg$score(121)
  expect_equal(leg$remain(), 120)
  expect_equal(leg$round(), 3)
  expect_equal(leg$status(), "ongoing")
  leg$score(120)
  expect_equal(leg$remain(), 0)
  expect_equal(leg$round(), 4)
  expect_equal(leg$status(), "finished")
})
